### PR TITLE
Fixing model lighting

### PR DESCRIPTION
**Pull request by Interrupt**

### CODE REVIEW

**Comment by inguin** [comment]
Looks like an opposite sign somewhere. The first camera in the healing suite is dark when the lights are on and vice versa.

**Comment by Interrupt** [comment]
Weird, that’s what I was using for testing. I’ll ABS it to be sure

**Comment by inguin** [comment]
Still no improvement. The camera is shaded when the lights are on and bright when the lights are off. Compare the software renderer (top) and the GL renderer (bottom):

screenshot demonstrating the issue

Using 1 - your light value makes this camera look good, but then others look wrong.

**Comment by inguin** [comment]
Still no change. So, this actually looks correct on your system? That's super-weird!

**Comment by Interrupt** [comment]
Found a real fix, I needed to do the same thing that you were doing for sprite lighting where you have to pluck the real value from the `grd_screen->ltab` table.

**Comment by inguin** [comment]
Yeah, that's it! :champagne: Had almost figured it out myself.

**Comment by inguin** [comment]
Squashed and merged manually.

**Pull request closed without merging**
